version: '3.7'
services: 
  mysql:
    image: mysql:latest 
    container_name: mysql-for-shop    
    environment: 
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}    
      MYSQL_USER: ${DATABASE_USER}  
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}     
    expose:  
      - "3306"
      
  web:  
    build: ./shop-ui
    container_name: shop-ui
    ports: 
      - "8080:8080"
    environment: 
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      JDBC_DATABASE_USERNAME: ${DATABASE_USER}
      JDBC_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect    
    depends_on: 
      - mysql          