# позволяет развернуть локальную версию сервисов докер
version: '3.7'
services: 
  mysql:
    image: mysql:latest     
    environment: 
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}    
      MYSQL_USER: ${DATABASE_USER}  
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}     
    expose:  
      - "3306"
  web:  
    image: maven:3.6.1-ibmjava-8-alpine  
    build: ./shop-ui/
    working_dir: /shop-ui/
    
    volumes:
      - ./shop-ui:/shop-ui
      - ~/.m2:/root/.m2
    ports: 
      - "8080:8080"
    environment: 
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      JDBC_DATABASE_USERNAME: ${DATABASE_USER}
      JDBC_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
    command: mvn clean spring-boot:run
    depends_on: 
      - mysql


    
