# позволяет развернуть локальную версию сервисов докер
version: '3.7'
services: 
  mysql:
    image: mysql:latest     
    environment: 
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}    
      MYSQL_USER: ${DATABASE_USER}  
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}     
    expose:  
      - "3306"
  web:  
    image: openjdk:8-jdk-alpine 
    ports: 
      - "8080:8080"
    environment: 
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      JDBC_DATABASE_USERNAME: ${DATABASE_USER}
      JDBC_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect    
    depends_on: 
      - mysql


    
